version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: bookcenter-db
    environment:
      MYSQL_DATABASE: bookcenter
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bookcenter-network

volumes:
  mysql_data:

networks:
  bookcenter-network:
